{% set version = "1.3.3" %}

package:
  name: pvxs
  version: "{{ version }}"

source:
  url: https://github.com/epics-base/pvxs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 944d16687fbdd31f43c617824048891756ff9edd93d209df260b17d2adc0b446
  patches:
    - 0001-Add-environment-variable-for-softIocPVX.dbd.patch

build:
  skip: True  # [win or osx]
  number: 0
  run_exports:
    - {{ pin_subpackage('pvxs', max_pin='x.x.x') }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - epics-base
    - libevent

test:
  commands:
    - pvxcall -V
    - pvxget -V
    - pvxinfo -V
    - pvxlist -V
    - pvxmonitor -V
    - pvxmshim -V
    - pvxput -V
    - pvxvct -V
    - softIocPVX -V
  files:
    - lib/libpvxs.so
    - lib/libpvxsIoc.so
    - include/pvxs/version.h

about:
  home: https://github.com/epics-base/pvxs/
  license: BSD-4-Clause-UC
  license_family: BSD
  license_file: LICENSE
  summary: Library and a set of CLI utilities acting as PVAccess protocol client and/or server
  doc_url: https://epics-base.github.io/pvxs/

extra:
  recipe-maintainers:
    - lucmaga
    - aharrisson
